<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>ai-meeting</artifactId>
        <groupId>ai-meeting</groupId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>ai-meeting-boot</artifactId>
    <packaging>jar</packaging>

    <name>ai-meeting-boot</name>
    <url>http://maven.apache.org</url>

    <dependencies>
        <!-- ======= -->
        <!-- 模块依赖 -->
        <!-- ======= -->
        <dependency>
            <groupId>ai-meeting</groupId>
            <artifactId>ai-meeting-api</artifactId>
        </dependency>
        <dependency>
            <groupId>ai-meeting</groupId>
            <artifactId>ai-meeting-application</artifactId>
        </dependency>
        <dependency>
            <groupId>ai-meeting</groupId>
            <artifactId>ai-meeting-infrastructure</artifactId>
        </dependency>
        <dependency>
            <groupId>ai-meeting</groupId>
            <artifactId>ai-meeting-domain</artifactId>
        </dependency>
        <dependency>
            <groupId>ai-meeting</groupId>
            <artifactId>ai-meeting-common</artifactId>
        </dependency>
        
        <!-- ======= -->
        <!-- 三方依赖 -->
        <!-- ======= -->
        <!-- Spring Boot Starter Web -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <!-- H2数据库 -->
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>runtime</scope>
        </dependency>
        <!-- Spring Boot JDBC Starter -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
        </dependency>
    </dependencies>

    <build>
        <finalName>ai-meeting-boot</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring.boot.version}</version>
                <configuration>
                    <mainClass>com.only.ai.boot.SimpleStarter</mainClass>
                    <layout>ZIP</layout>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
